// Deterministic mock dataset for the visual-reference demo route
// (/architecture-02/review-demo). This route exists ONLY to let a
// stakeholder compare pixel/visual fidelity against a reference screenshot
// with a fully-populated dashboard -- it is NOT the real product surface.
// The actual Review page (/architecture-02?deck=review) reads live data
// from review_daily_summary() / review_consistency() / study_profile() and
// deliberately never fabricates a number (see those RPCs' own comments).
//
// Every value here is generated by a seeded PRNG (seeded-random.ts), so the
// dataset is stable across reloads -- not fresh random noise every render --
// but it is still entirely synthetic.

import { hashString, mulberry32 } from "@/lib/review-demo/seeded-random";

export interface ReviewDemoSession {
  startHour: number;
  minutes: number;
}

export interface ReviewDemoDay {
  date: string; // YYYY-MM-DD
  focusMinutes: number;
  plannedMinutes: number;
  tasksCompleted: number;
  tasksPlanned: number;
  sessions: ReviewDemoSession[];
  interruptions: number;
  rescheduled: number;
  xp: number;
  xpTarget: number;
  effortScore: number; // 0-100
  subjects: {
    backend: number;
    dsa: number;
    sql: number;
    systemDesign: number;
  };
}

const SEED = hashString("mtdo-review-demo-v1");
const DAY_COUNT = 365;
const TODAY = new Date("2026-09-14T00:00:00Z");

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function monthDensity(month: number): number {
  // Stronger Jan-Apr density, a dip mid-year, active Sep end -- matches the
  // reference screenshot's visual clustering, not real usage.
  const table = [0.55, 0.7, 0.8, 0.75, 0.6, 0.4, 0.35, 0.45, 0.65, 0.5, 0.4, 0.5];
  return table[month]!;
}

function buildDay(date: Date, rand: () => number, forcedToday: boolean): ReviewDemoDay {
  const month = date.getUTCMonth();
  const density = monthDensity(month);
  const weekday = date.getUTCDay();
  const isWeekend = weekday === 0 || weekday === 6;
  const active = forcedToday || rand() < density * (isWeekend ? 0.6 : 1);

  if (!active) {
    return {
      date: isoDate(date),
      focusMinutes: 0,
      plannedMinutes: Math.round(60 + rand() * 60),
      tasksCompleted: 0,
      tasksPlanned: Math.round(rand() * 3),
      sessions: [],
      interruptions: 0,
      rescheduled: rand() < 0.3 ? 1 : 0,
      xp: 0,
      xpTarget: 40,
      effortScore: 0,
      subjects: { backend: 0, dsa: 0, sql: 0, systemDesign: 0 },
    };
  }

  if (forcedToday) {
    return {
      date: isoDate(date),
      focusMinutes: 103,
      plannedMinutes: 120,
      tasksCompleted: 5,
      tasksPlanned: 7,
      sessions: [
        { startHour: 8, minutes: 47 },
        { startHour: 11, minutes: 34 },
        { startHour: 16, minutes: 22 },
      ],
      interruptions: 4,
      rescheduled: 2,
      xp: 68,
      xpTarget: 100,
      effortScore: 71,
      subjects: { backend: 38, dsa: 31, sql: 17, systemDesign: 14 },
    };
  }

  const sessionCount = 1 + Math.floor(rand() * 4);
  const sessions: ReviewDemoSession[] = [];
  for (let i = 0; i < sessionCount; i++) {
    sessions.push({
      startHour: 7 + Math.floor(rand() * 14),
      minutes: 15 + Math.floor(rand() * 60),
    });
  }
  const focusMinutes = sessions.reduce((sum, s) => sum + s.minutes, 0);
  const plannedMinutes = Math.round(focusMinutes * (0.8 + rand() * 0.5));
  const tasksPlanned = 2 + Math.floor(rand() * 6);
  const tasksCompleted = Math.min(tasksPlanned, Math.round(tasksPlanned * (0.4 + rand() * 0.6)));
  const effortScore = Math.min(100, Math.round((focusMinutes / 150) * 60 + (tasksCompleted / Math.max(1, tasksPlanned)) * 40));

  const backend = Math.round(20 + rand() * 30);
  const dsa = Math.round(10 + rand() * 30);
  const sql = Math.round(5 + rand() * 20);
  const systemDesign = Math.max(0, 100 - backend - dsa - sql);

  return {
    date: isoDate(date),
    focusMinutes,
    plannedMinutes,
    tasksCompleted,
    tasksPlanned,
    sessions,
    interruptions: Math.floor(rand() * 5),
    rescheduled: Math.floor(rand() * 3),
    xp: Math.round(effortScore * 0.9),
    xpTarget: 100,
    effortScore,
    subjects: { backend, dsa, sql, systemDesign },
  };
}

function generate(): ReviewDemoDay[] {
  const rand = mulberry32(SEED);
  const days: ReviewDemoDay[] = [];
  for (let i = DAY_COUNT - 1; i >= 0; i--) {
    const d = new Date(TODAY);
    d.setUTCDate(d.getUTCDate() - i);
    days.push(buildDay(d, rand, i === 0));
  }
  return days;
}

let cache: ReviewDemoDay[] | null = null;

export function getReviewDemoDays(): ReviewDemoDay[] {
  if (!cache) cache = generate();
  return cache;
}

export function getReviewDemoToday(): ReviewDemoDay {
  return getReviewDemoDays().at(-1)!;
}
