// Round-trip and tamper-resistance for the refresh-token envelope
// (migrations/0020, decisions.md 2026-09-11). The GCM auth tag is the reason
// this is AES-256-GCM rather than CBC -- a corrupted ciphertext must fail
// loudly rather than decrypt to garbage that then gets sent to Google as a
// credential, and that claim is what the tamper tests below actually check.
import { randomBytes } from "node:crypto";
import { describe, expect, it } from "vitest";

import {
  CalendarCryptoError,
  decryptRefreshToken,
  encryptRefreshToken,
  generateEncryptionKey,
  parseEncryptionKey,
} from "./crypto";

const KEY = randomBytes(32);
const TOKEN = "1//0gFAKE-refresh-token-value_with.symbols";

describe("parseEncryptionKey", () => {
  it("returns null for an absent key", () => {
    expect(parseEncryptionKey(undefined)).toBeNull();
    expect(parseEncryptionKey("")).toBeNull();
  });

  it("returns null for a present but wrong-length key", () => {
    // This is the case that matters: Buffer.from(_, "base64") is lenient and
    // silently drops invalid characters, so a short or garbage value decodes
    // "successfully" into the wrong number of bytes rather than throwing.
    expect(parseEncryptionKey(randomBytes(16).toString("base64"))).toBeNull();
    expect(parseEncryptionKey("not-a-key")).toBeNull();
  });

  it("accepts a key generated by generateEncryptionKey()", () => {
    expect(parseEncryptionKey(generateEncryptionKey())?.length).toBe(32);
  });
});

describe("refresh token envelope", () => {
  it("round-trips a token", () => {
    expect(decryptRefreshToken(encryptRefreshToken(TOKEN, KEY), KEY)).toBe(TOKEN);
  });

  it("never stores the token in the clear", () => {
    expect(encryptRefreshToken(TOKEN, KEY)).not.toContain(TOKEN);
  });

  it("uses a fresh IV per call, so the same token encrypts differently twice", () => {
    expect(encryptRefreshToken(TOKEN, KEY)).not.toBe(encryptRefreshToken(TOKEN, KEY));
  });

  it("tags the envelope with a version, so a later key rotation can recognise old rows", () => {
    expect(encryptRefreshToken(TOKEN, KEY).startsWith("v1:")).toBe(true);
  });

  it("rejects a tampered ciphertext instead of returning garbage", () => {
    const envelope = encryptRefreshToken(TOKEN, KEY);
    const parts = envelope.split(":");
    const flipped = Buffer.from(parts[3]!, "base64");
    flipped[0] = flipped[0]! ^ 0xff;
    parts[3] = flipped.toString("base64");
    expect(() => decryptRefreshToken(parts.join(":"), KEY)).toThrow(CalendarCryptoError);
  });

  it("rejects the wrong key", () => {
    expect(() => decryptRefreshToken(encryptRefreshToken(TOKEN, KEY), randomBytes(32))).toThrow(
      CalendarCryptoError,
    );
  });

  it("rejects a malformed or unknown-version envelope", () => {
    expect(() => decryptRefreshToken("nonsense", KEY)).toThrow(CalendarCryptoError);
    expect(() => decryptRefreshToken("v2:a:b:c", KEY)).toThrow(CalendarCryptoError);
  });

  it("does not echo the underlying crypto error to the caller", () => {
    // The caller's only correct response is "ask the user to reconnect"; the
    // difference between a wrong key and a tampered blob is not something an
    // error string should be leaking.
    try {
      decryptRefreshToken(encryptRefreshToken(TOKEN, KEY), randomBytes(32));
      throw new Error("expected a throw");
    } catch (err) {
      expect((err as Error).message).toBe(
        "Stored calendar token could not be decrypted. Reconnect the calendar.",
      );
    }
  });
});
